# Generated by Django 5.1.2 on 2024-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('number_of_questions', models.IntegerField()),
                ('passing_score', models.DecimalField(decimal_places=2, help_text='Minimum score to pass', max_digits=5)),
                ('exam_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('oral', 'Oral')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
