# Generated by Django 5.1.2 on 2024-10-29 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='max_score',
            field=models.IntegerField(default=0, help_text='Maximum score achievable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='pass_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum score to pass', max_digits=5),
            preserve_default=False,
        ),
    ]
