# Generated by Django 5.1.2 on 2024-10-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_examen_date_examen_max_score_examen_pass_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='pass_score',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='updated_at',
        ),
    ]
