# Generated by Django 5.1.2 on 2024-10-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_remove_examen_created_at_remove_examen_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('open', 'Open-ended Question'), ('true_false', 'True/False')], max_length=10)),
                ('options', models.JSONField(blank=True, help_text='For MCQ, store options as JSON', null=True)),
                ('correct_answer', models.TextField(help_text='Correct answer or correct option for MCQ')),
                ('points', models.DecimalField(decimal_places=2, help_text='Points for this question', max_digits=5)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examen.examen')),
            ],
        ),
    ]
