# Generated by Django 5.1.2 on 2024-10-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_questionexamen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionexamen',
            name='examen',
        ),
    ]
