# Generated by Django 4.2 on 2024-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
