# Generated by Django 4.2 on 2024-10-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chapter', '0001_initial'),
        ('satisfaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='note',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='formulaire',
            name='type_formulaire',
            field=models.CharField(choices=[('chapitre', 'Chapitre'), ('cours_final', 'Cours Final')], default='chapitre', max_length=20),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to='Chapter.chapter'),
        ),
    ]
