# Generated by Django 4.2 on 2024-10-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satisfaction', '0003_rapport_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formulaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='Course.course'),
        ),
    ]
