# Generated by Django 5.1.2 on 2024-10-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
