# Generated by Django 5.1.2 on 2024-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facial_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
