# Generated by Django 5.1.2 on 2024-10-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_user_facial_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facial_encoding',
        ),
    ]
